meta: #which modules you would like to run
  runName: simulationTest
  saveRun: no #saves the generated model and validation results file.

paths: 
  simRunner: simulations/randomDefects/runSim.py
  simFunc: runSim #this is the method that will be called on the simRunner file
  fileConvert: ImageAnnotation

simulation:
  images: 1
  numDefects: 20 #number of defects per image
  minDefects: 10
  maxDefects: 50
  xDim: 250
  yDim: 200
  decrossMax: 50
  decrossMin: 50